//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.NotesSampleDataSource
{
    using System; 
    using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
    internal class NotesSampleDataSource { }
#else

    public class NotesSampleDataSource : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public NotesSampleDataSource()
        {
            try
            {
                Uri resourceUri = new Uri("ms-appx:/SampleData/NotesSampleDataSource/NotesSampleDataSource.xaml", UriKind.RelativeOrAbsolute);
                Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
            }
            catch
            {
            }
        }

        private Notes _Notes = new Notes();

        public Notes Notes
        {
            get
            {
                return this._Notes;
            }
        }
    }

    public class NotesItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private string _Created = string.Empty;

        public string Created
        {
            get
            {
                return this._Created;
            }

            set
            {
                if (this._Created != value)
                {
                    this._Created = value;
                    this.OnPropertyChanged("Created");
                }
            }
        }

        private string _NoteText = string.Empty;

        public string NoteText
        {
            get
            {
                return this._NoteText;
            }

            set
            {
                if (this._NoteText != value)
                {
                    this._NoteText = value;
                    this.OnPropertyChanged("NoteText");
                }
            }
        }

        private string _Title = string.Empty;

        public string Title
        {
            get
            {
                return this._Title;
            }

            set
            {
                if (this._Title != value)
                {
                    this._Title = value;
                    this.OnPropertyChanged("Title");
                }
            }
        }
    }

    public class Notes : System.Collections.ObjectModel.ObservableCollection<NotesItem>
    { 
    }
#endif
}
